version: "3"

services:
     strapi-client:
          image: strapi/strapi
          container_name: strapi-client
          restart: unless-stopped
          env_file: .env
          environment:
               DATABASE_CLIENT: ${DATABASE_CLIENT}
               DATABASE_NAME: ${DATABASE_NAME}
               DATABASE_HOST: ${DATABASE_HOST}
               DATABASE_PORT: ${DATABASE_PORT}
               DATABASE_USERNAME: ${DATABASE_USERNAME}
               DATABASE_PASSWORD: ${DATABASE_PASSWORD}
          networks:
               - strapi-network
          volumes:
               - ./app:/srv/app
          ports:
               - "1337:1337"

     mongodb:
          image: mongo
          container_name: mongodb
          restart: unless-stopped
          env_file: .env
          environment:
               MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
               MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
          networks:
               - strapi-network
          volumes:
               - strapidata:/data/db
          ports:
               - "27017:27017"

     client:
          image: client
          container_name: client-react
          restart: always
          build:
               context: ./client/ignium-digital
               dockerfile: Dockerfile
          networks:
               - strapi-network
          volumes:
               - "./client/ignium-digital:/app"
               - "/app/node_modules"
          ports:
               - 3000:3000
          env_file: .env

networks:
     strapi-network:
          driver: bridge

volumes:
     strapidata:
